### ISSUE TITLE
Global config not set

### ISSUE THREAD

**Issue by zenbrent** [cmawhorter/betty#49]
When I run `betty update --region us-east-1` (or `publish`) it gives this error:

```
/Users/brentbrimhall/code/das/cloudfront-spa/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'name' of null
    at Object.<anonymous> (/Users/brentbrimhall/code/das/cloudfront-spa/node_modules/bty/cli/commands/logs.js:21:34)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at requireDir (/Users/brentbrimhall/code/das/cloudfront-spa/node_modules/require-dir/index.js:123:33)
    at Object.<anonymous> (/Users/brentbrimhall/code/das/cloudfront-spa/node_modules/bty/cli/cli.js:9:36)
```

It's trying to read `global.config.name`.

**Comment by cmawhorter** [comment]
the readme is out of date.  i'm working on fixing that now.  there are a few ways to configure things, but the most straightforward way to get started is:

1. `$ export AWS_PROFILE=...; export AWS_REGION=...` -- these are same as aws cli
1. `$ betty deploy` -- this does a `build` && `update`

A proper getting started is TODO but [this repo](https://github.com/cmawhorter/betty-ddb-crud-microservice) and [video](https://www.youtube.com/watch?v=kFeWzsVAsKg) shows how to set up a new project.

**Comment by cmawhorter** [comment]
Just updated the readme.  It's [available here](https://github.com/cmawhorter/betty/tree/9050d79158fcabb2443f59db110c7ab77e7bd13f) until I merge and release alpha2
